import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Changa_One, Jost } from "next/font/google";
import NavBar from "@/components/templates/header/NavBar";

const changaOne = Changa_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-changa",
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        changaOne.variable,
        jost.variable,
        "font-sans",
      )}>
      <body className="min-h-full flex flex-col">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
